version: "3.8"

services:


  redis:
    image: redis
    restart: always

  backend:
    restart: always
    build:
      context: /api
    ports:
      - "8000:8000"
    command: [ "python", "/api/manage.py", "runserver", "0.0.0.0:8000"]


  db:
    container_name: pg_db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_db
    volumes:
      - /postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: lollololol686@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"


  worker:
    restart: always
    build:
      context: /api
    command: ['celery', '-A', 'api', 'worker' ]